HMT/Models/DomainModels/Sale.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HMT.Models
{
    public class Sale
    {
        public int SaleID { get; set; }
        public DateTime Date { get; set; }
        public int StoreID { get; set; }
        public int CustomerID { get; set; }
        public Store Store { get; set; }
        public Customer Customer { get; set; }
        public ICollection<Sold> Solds { get; set; }
    }
}

HMT/Controllers/SaleController.cs
using HMT.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HMT.Controllers
{
    public class SaleController : Controller
    {
        private HMTContext context { get; set; }

        public SaleController(HMTContext ctx)
        {
            context = ctx;
        }
        public IActionResult Index(string id)
        {
            var filters = new Filter(id);
            ViewBag.Filter = filters;
            ViewBag.Customers = context.Customers.OrderBy(c => c.Name).ToList();
            ViewBag.Stores = context.Stores.OrderBy(s => s.StoreID).ToList();
            IQueryable<Sale> query = context.Sales.Include(c => c.Customer).Include(s => s.Store);
            if (filters.HasCustomer)
            {
                query = query.Where(c => c.CustomerID.ToString() == filters.CustomerID.ToString());
            }
            if (filters.HasStore)
            {
                query = query.Where(s => s.StoreID.ToString() == filters.StoreID.ToString());
            }
            var sales = query.OrderBy(s => s.SaleID).ToList();
            return View(sales);
        }
        [HttpPost]
        public IActionResult Filter(string[] filter)
        {
            string id = string.Join('-', filter);
            return RedirectToAction("Index", new { ID = id });
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Customers = context.Customers.ToList();
            ViewBag.Stores = context.Stores.ToList();
            var s = context.Sales.Find(id);
            return View(s);
        }
        [HttpPost]
        public IActionResult Edit(Sale s)
        {
            if (ModelState.IsValid)
            {
                context.Sales.Update(s);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Customers = context.Customers.ToList();
                ViewBag.Stores = context.Stores.ToList();
                return View(s);
            }
        }
        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Customers = context.Customers.ToList();
            ViewBag.Stores = context.Stores.ToList();
            return View();
        }
        [HttpPost]
        public IActionResult Add (Sale s)
        {
            if (ModelState.IsValid)
            {
                context.Sales.Add(s);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Customers = context.Customers.ToList();
                ViewBag.Stores = context.Stores.ToList();
                return View(s);
            }
        }

        [HttpGet]
        public IActionResult Delete (int id)
        {
            ViewBag.Customers = context.Customers.ToList();
            ViewBag.Stores = context.Stores.ToList();
            var s = context.Sales.Find(id);
            return View(s);
        }
        [HttpPost]
        public IActionResult Delete (Sale s)
        {
            if(ModelState.IsValid)
            {
                context.Sales.Remove(s);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Customers = context.Customers.ToList();
                ViewBag.Stores = context.Stores.ToList();
                return View(s);
            }
        }         
    }
}

HMT/Views/Sale/Add.cshtml
@model Sale

<h3>Add Transactions</h3>
<form asp-action="Add">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Date">Date:</label>
        <input type="text" asp-for="Date" class="form-control" />
        <span asp-validation-for="Date" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="StoreID">Store:</label>
        <select asp-for="StoreID" class="form-control"
                asp-items="@(new SelectList(ViewBag.Stores, "StoreID","StoreID"))">
            <option value=""></option>
        </select>
        <span asp-validation-for="StoreID" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="CustomerID">Customer:</label>
        <select asp-for="CustomerID" class="form-control"
                asp-items="@(new SelectList(ViewBag.Customers, "CustomerID","CustomerID"))">
            <option value=""></option>
        </select>
        <span asp-validation-for="CustomerID" class="text-danger"></span>
    </div>

    <div class="form-group">
        <input type="submit" value="Add" class="btn btn-info" />
        <a asp-action="Index" class="btn btn-warning">Cancel</a>
    </div>
</form>

HMT/Views/Sale/Delete.cshtml
@model Sale
@{
    ViewData["Title"] = "Delete";
}

<h3>Delete</h3>
<h4>Are you sure you want to delete this transaction?</h4>
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Store)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Store.StoreID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Customer.Name)
        </dd>
    </dl>
    <form asp-action="Delete" method="post">
        <input type="hidden" asp-for="SaleID" />
        <button type="submit" class="btn btn-danger"> Delete </button>
        <a asp-controller="Sale" asp-action="Index" class="btn btn-warning">Cancel</a>
    </form>
</div>

HMT/Views/Sale/Edit.cshtml
@model Sale

<h3>Edit Transactions</h3>
<form asp-action="Edit" >
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="SaleID" />
    <div class="form-group">
        <label asp-for="Date">Date:</label>
        <input type="text" asp-for="Date" class="form-control" />
        <span asp-validation-for="Date" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="StoreID">Store:</label>
        <select asp-for="StoreID" class="form-control"
                asp-items="@(new SelectList(ViewBag.Stores, "StoreID","StoreID"))">
            <option value=""></option>
        </select>
        <span asp-validation-for="StoreID" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="CustomerID">Customer:</label>
        <select asp-for="CustomerID" class="form-control"
                asp-items="@(new SelectList(ViewBag.Customers, "CustomerID","CustomerID"))">
            <option value=""></option>
        </select>
        <span asp-validation-for="CustomerID" class="text-danger"></span>
    </div>

    <div class="form-group">
        <input type="submit" value="Edit" class="btn btn-info" />
        <a asp-action="Index" class="btn btn-warning">Cancel</a>
    </div>
</form>

HMT/Views/Sale/Index.cshtml
@model List<Sale>

@{
    ViewBag.Title = "Sales";
}
<div class="row">
    <div class="col-sm-2">
        <form asp-action="Filter" method="post">
            <div class="form-group">
                <label>Customer:</label>
                <select name="filter" class="form-control"
                        asp-items="@(new SelectList(ViewBag.Customers,
                    "CustomerID", "Name", ViewBag.Filter.CustomerID))">
                    <option value="all">All</option>
                </select>
            </div>

            <div class="form-group">
                <label>Store:</label>
                <select name="filter" class="form-control"
                        asp-items="@(new SelectList(ViewBag.Stores,
                    "StoreID", "StoreID", ViewBag.Filter.StoreID))">
                    <option value="all">All</option>
                </select>
            </div>
            <button type="submit" class="btn btn-info">Filter</button>
            <a asp-action="Index" asp-route-id="" class="btn btn-info">Clear</a>
        </form>
    </div>
    <div class="col-sm-10">
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Date</th>
                    <th>Store</th>
                    <th>Customer</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var s in Model)
                {
                    <tr>
                        <td>@s.SaleID</td>
                        <td>@s.Date</td>
                        <td>@s.Store.StoreID</td>
                        <td>@s.Customer.Name</td>

                        <td>
                                <a asp-controller="Sale" asp-action="Edit" asp-route-id=@s.SaleID class="btn btn-info"> Edit </a>
                                <a asp-controller="Sale" asp-action="Delete" asp-route-id="@s.SaleID" class="btn btn-info"> Delete </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <a asp-controller="Sale" asp-action="Add" class="btn btn-info"> Add Sales</a>       
    </div>
</div>